# Generated by Django 4.1.5 on 2023-01-31 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0078_referenceindex"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServicePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("beta_id", models.CharField(max_length=255, verbose_name="ID beta")),
                (
                    "beta_name",
                    models.CharField(max_length=255, verbose_name="Nom du service"),
                ),
                ("beta_pitch", models.CharField(max_length=255, verbose_name="Pitch")),
                (
                    "beta_link",
                    models.URLField(blank=True, max_length=255, verbose_name="Lien vers le service"),
                ),
                (
                    "beta_problem",
                    models.TextField(blank=True, verbose_name="Le problème"),
                ),
                (
                    "beta_service",
                    models.TextField(blank=True, verbose_name="Notre service"),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
