# Generated by Django 4.1.5 on 2023-02-01 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0002_servicepage_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicepage",
            name="beta_last_phase",
            field=models.CharField(
                blank=True,
                choices=[
                    ("success", "Pérennisé"),
                    ("transfer", "Transfert"),
                    ("acceleration", "Accélération"),
                    ("construction", "Construction"),
                    ("investigation", "Investigation"),
                    ("alumni", "Partenariats terminés"),
                ],
                max_length=20,
                verbose_name="Maturité",
            ),
        ),
    ]
