# Generated by Django 4.1.5 on 2023-03-01 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailimages", "0024_index_image_file_hash"),
        ("services", "0005_alter_servicepage_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicepage",
            name="banner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="Bannière",
            ),
        ),
        migrations.AddField(
            model_name="servicepage",
            name="logo",
            field=models.ForeignKey(
                blank=True,
                help_text="Format préconisé : png en 128px par 128px",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="Logo",
            ),
        ),
    ]
