# Generated by Django 4.1.5 on 2023-04-14 12:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0007_alter_servicepage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicepage",
            name="beta_id",
            field=models.CharField(max_length=255, unique=True, verbose_name="ID beta"),
        ),
        migrations.CreateModel(
            name="Member",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("beta_id", models.CharField(max_length=255, unique=True, verbose_name="ID beta")),
                ("beta_fullname", models.CharField(max_length=255, verbose_name="Prénom et nom")),
                ("beta_role", models.CharField(max_length=255, verbose_name="Poste")),
                ("beta_domaine", models.CharField(max_length=255, verbose_name="Domaine")),
                ("beta_github", models.CharField(max_length=255, verbose_name="Github")),
                ("services", models.ManyToManyField(blank=True, to="services.servicepage")),
            ],
        ),
    ]
