# Generated by Django 4.1.5 on 2023-06-01 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0008_alter_servicepage_beta_id_member"),
        ("services", "0008_alter_servicepage_body"),
    ]

    operations = []
